// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BaseAccount$Type } from "./BaseAccount";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BaseAccount"]: BaseAccount$Type;
    ["@account-abstraction/contracts/core/BaseAccount.sol:BaseAccount"]: BaseAccount$Type;
  }

  interface ContractTypesMap {
    ["BaseAccount"]: GetContractReturnType<BaseAccount$Type["abi"]>;
    ["@account-abstraction/contracts/core/BaseAccount.sol:BaseAccount"]: GetContractReturnType<BaseAccount$Type["abi"]>;
  }
}
