// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SimpleAccountFactory$Type } from "./SimpleAccountFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimpleAccountFactory"]: SimpleAccountFactory$Type;
    ["@account-abstraction/contracts/samples/SimpleAccountFactory.sol:SimpleAccountFactory"]: SimpleAccountFactory$Type;
  }

  interface ContractTypesMap {
    ["SimpleAccountFactory"]: GetContractReturnType<SimpleAccountFactory$Type["abi"]>;
    ["@account-abstraction/contracts/samples/SimpleAccountFactory.sol:SimpleAccountFactory"]: GetContractReturnType<SimpleAccountFactory$Type["abi"]>;
  }
}
