// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IEntryPoint$Type } from "./IEntryPoint";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEntryPoint"]: IEntryPoint$Type;
    ["@account-abstraction/contracts/interfaces/IEntryPoint.sol:IEntryPoint"]: IEntryPoint$Type;
  }

  interface ContractTypesMap {
    ["IEntryPoint"]: GetContractReturnType<IEntryPoint$Type["abi"]>;
    ["@account-abstraction/contracts/interfaces/IEntryPoint.sol:IEntryPoint"]: GetContractReturnType<IEntryPoint$Type["abi"]>;
  }
}
