// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BasePaymaster$Type } from "./BasePaymaster";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BasePaymaster"]: BasePaymaster$Type;
    ["@account-abstraction/contracts/core/BasePaymaster.sol:BasePaymaster"]: BasePaymaster$Type;
  }

  interface ContractTypesMap {
    ["BasePaymaster"]: GetContractReturnType<BasePaymaster$Type["abi"]>;
    ["@account-abstraction/contracts/core/BasePaymaster.sol:BasePaymaster"]: GetContractReturnType<BasePaymaster$Type["abi"]>;
  }
}
