// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Errors$Type } from "./Errors";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Errors"]: Errors$Type;
    ["@openzeppelin/contracts/utils/Errors.sol:Errors"]: Errors$Type;
  }

  interface ContractTypesMap {
    ["Errors"]: GetContractReturnType<Errors$Type["abi"]>;
    ["@openzeppelin/contracts/utils/Errors.sol:Errors"]: GetContractReturnType<Errors$Type["abi"]>;
  }
}
