version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "sa-east-1"
resolve_s3 = true
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"

