// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IWakeUpPaymaster$Type } from "./IWakeUpPaymaster";
import { IWakeUpPaymasterErrors$Type } from "./IWakeUpPaymasterErrors";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IWakeUpPaymaster"]: IWakeUpPaymaster$Type;
    ["IWakeUpPaymasterErrors"]: IWakeUpPaymasterErrors$Type;
    ["contracts/interfaces/Paymaster.sol:IWakeUpPaymaster"]: IWakeUpPaymaster$Type;
    ["contracts/interfaces/Paymaster.sol:IWakeUpPaymasterErrors"]: IWakeUpPaymasterErrors$Type;
  }

  interface ContractTypesMap {
    ["IWakeUpPaymaster"]: GetContractReturnType<IWakeUpPaymaster$Type["abi"]>;
    ["IWakeUpPaymasterErrors"]: GetContractReturnType<IWakeUpPaymasterErrors$Type["abi"]>;
    ["contracts/interfaces/Paymaster.sol:IWakeUpPaymaster"]: GetContractReturnType<IWakeUpPaymaster$Type["abi"]>;
    ["contracts/interfaces/Paymaster.sol:IWakeUpPaymasterErrors"]: GetContractReturnType<IWakeUpPaymasterErrors$Type["abi"]>;
  }
}
