// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IWakeUpPaymaster$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IWakeUpPaymaster",
  "sourceName": "contracts/interfaces/Paymaster.sol",
  "abi": [
    {
      "inputs": [],
      "name": "senderNotProvided",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allowAccount",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isAccountAllowed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "removeAccount",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IWakeUpPaymaster",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IWakeUpPaymaster$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/interfaces/Paymaster.sol:IWakeUpPaymaster",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IWakeUpPaymaster$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IWakeUpPaymaster",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IWakeUpPaymaster$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/interfaces/Paymaster.sol:IWakeUpPaymaster",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IWakeUpPaymaster$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IWakeUpPaymaster",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IWakeUpPaymaster$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/interfaces/Paymaster.sol:IWakeUpPaymaster",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IWakeUpPaymaster$Type["abi"]>>;
}
