// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NonceManager$Type } from "./NonceManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NonceManager"]: NonceManager$Type;
    ["@account-abstraction/contracts/core/NonceManager.sol:NonceManager"]: NonceManager$Type;
  }

  interface ContractTypesMap {
    ["NonceManager"]: GetContractReturnType<NonceManager$Type["abi"]>;
    ["@account-abstraction/contracts/core/NonceManager.sol:NonceManager"]: GetContractReturnType<NonceManager$Type["abi"]>;
  }
}
