// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EntryPoint$Type } from "./EntryPoint";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EntryPoint"]: EntryPoint$Type;
    ["@account-abstraction/contracts/core/EntryPoint.sol:EntryPoint"]: EntryPoint$Type;
  }

  interface ContractTypesMap {
    ["EntryPoint"]: GetContractReturnType<EntryPoint$Type["abi"]>;
    ["@account-abstraction/contracts/core/EntryPoint.sol:EntryPoint"]: GetContractReturnType<EntryPoint$Type["abi"]>;
  }
}
