// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC1967Utils$Type } from "./ERC1967Utils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1967Utils"]: ERC1967Utils$Type;
    ["@openzeppelin/contracts/proxy/ERC1967/ERC1967Utils.sol:ERC1967Utils"]: ERC1967Utils$Type;
  }

  interface ContractTypesMap {
    ["ERC1967Utils"]: GetContractReturnType<ERC1967Utils$Type["abi"]>;
    ["@openzeppelin/contracts/proxy/ERC1967/ERC1967Utils.sol:ERC1967Utils"]: GetContractReturnType<ERC1967Utils$Type["abi"]>;
  }
}
