// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { INonceManager$Type } from "./INonceManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["INonceManager"]: INonceManager$Type;
    ["@account-abstraction/contracts/interfaces/INonceManager.sol:INonceManager"]: INonceManager$Type;
  }

  interface ContractTypesMap {
    ["INonceManager"]: GetContractReturnType<INonceManager$Type["abi"]>;
    ["@account-abstraction/contracts/interfaces/INonceManager.sol:INonceManager"]: GetContractReturnType<INonceManager$Type["abi"]>;
  }
}
