// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IEntryPointSimulations$Type } from "./IEntryPointSimulations";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEntryPointSimulations"]: IEntryPointSimulations$Type;
    ["@account-abstraction/contracts/interfaces/IEntryPointSimulations.sol:IEntryPointSimulations"]: IEntryPointSimulations$Type;
  }

  interface ContractTypesMap {
    ["IEntryPointSimulations"]: GetContractReturnType<IEntryPointSimulations$Type["abi"]>;
    ["@account-abstraction/contracts/interfaces/IEntryPointSimulations.sol:IEntryPointSimulations"]: GetContractReturnType<IEntryPointSimulations$Type["abi"]>;
  }
}
