// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Create2$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Create2",
  "sourceName": "@openzeppelin/contracts/utils/Create2.sol",
  "abi": [
    {
      "inputs": [],
      "name": "Create2EmptyBytecode",
      "type": "error"
    }
  ],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220960689407af79c5cf8bf429c619ae1a3f4223cf914f5d96d64b4aef88aee328f64736f6c634300081d0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220960689407af79c5cf8bf429c619ae1a3f4223cf914f5d96d64b4aef88aee328f64736f6c634300081d0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Create2",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Create2$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Create2.sol:Create2",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Create2$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Create2",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Create2$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Create2.sol:Create2",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Create2$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Create2",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Create2$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Create2.sol:Create2",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Create2$Type["abi"]>>;
}
