// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { WakeUpEntryPointSimulations$Type } from "./WakeUpEntryPointSimulations";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["WakeUpEntryPointSimulations"]: WakeUpEntryPointSimulations$Type;
    ["contracts/mocks/EntryPointSimulations.sol:WakeUpEntryPointSimulations"]: WakeUpEntryPointSimulations$Type;
  }

  interface ContractTypesMap {
    ["WakeUpEntryPointSimulations"]: GetContractReturnType<WakeUpEntryPointSimulations$Type["abi"]>;
    ["contracts/mocks/EntryPointSimulations.sol:WakeUpEntryPointSimulations"]: GetContractReturnType<WakeUpEntryPointSimulations$Type["abi"]>;
  }
}
