// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EntryPointMock$Type } from "./EntryPointMock";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EntryPointMock"]: EntryPointMock$Type;
    ["contracts/mocks/EntryPointMock.sol:EntryPointMock"]: EntryPointMock$Type;
  }

  interface ContractTypesMap {
    ["EntryPointMock"]: GetContractReturnType<EntryPointMock$Type["abi"]>;
    ["contracts/mocks/EntryPointMock.sol:EntryPointMock"]: GetContractReturnType<EntryPointMock$Type["abi"]>;
  }
}
