// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EntryPointSimulations$Type } from "./EntryPointSimulations";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EntryPointSimulations"]: EntryPointSimulations$Type;
    ["@account-abstraction/contracts/core/EntryPointSimulations.sol:EntryPointSimulations"]: EntryPointSimulations$Type;
  }

  interface ContractTypesMap {
    ["EntryPointSimulations"]: GetContractReturnType<EntryPointSimulations$Type["abi"]>;
    ["@account-abstraction/contracts/core/EntryPointSimulations.sol:EntryPointSimulations"]: GetContractReturnType<EntryPointSimulations$Type["abi"]>;
  }
}
