// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IAccountExecute$Type } from "./IAccountExecute";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IAccountExecute"]: IAccountExecute$Type;
    ["@account-abstraction/contracts/interfaces/IAccountExecute.sol:IAccountExecute"]: IAccountExecute$Type;
  }

  interface ContractTypesMap {
    ["IAccountExecute"]: GetContractReturnType<IAccountExecute$Type["abi"]>;
    ["@account-abstraction/contracts/interfaces/IAccountExecute.sol:IAccountExecute"]: GetContractReturnType<IAccountExecute$Type["abi"]>;
  }
}
