// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SimpleAccount$Type } from "./SimpleAccount";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimpleAccount"]: SimpleAccount$Type;
    ["@account-abstraction/contracts/samples/SimpleAccount.sol:SimpleAccount"]: SimpleAccount$Type;
  }

  interface ContractTypesMap {
    ["SimpleAccount"]: GetContractReturnType<SimpleAccount$Type["abi"]>;
    ["@account-abstraction/contracts/samples/SimpleAccount.sol:SimpleAccount"]: GetContractReturnType<SimpleAccount$Type["abi"]>;
  }
}
