// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC1967Proxy$Type } from "./ERC1967Proxy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1967Proxy"]: ERC1967Proxy$Type;
    ["@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol:ERC1967Proxy"]: ERC1967Proxy$Type;
  }

  interface ContractTypesMap {
    ["ERC1967Proxy"]: GetContractReturnType<ERC1967Proxy$Type["abi"]>;
    ["@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol:ERC1967Proxy"]: GetContractReturnType<ERC1967Proxy$Type["abi"]>;
  }
}
