// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface UserOperationLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "UserOperationLib",
  "sourceName": "@account-abstraction/contracts/core/UserOperationLib.sol",
  "abi": [
    {
      "inputs": [],
      "name": "PAYMASTER_DATA_OFFSET",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "PAYMASTER_POSTOP_GAS_OFFSET",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "PAYMASTER_VALIDATION_GAS_OFFSET",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x60a96037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060475760003560e01c806325093e1b14604c578063b29a8ff4146065578063ede3150214606c575b600080fd5b6053602481565b60405190815260200160405180910390f35b6053601481565b605360348156fea2646970667358221220da135c71a84f8772d340dad3ef25a88ef16c8f7e3feb19b238a41a8d27cf79ca64736f6c634300081d0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040526004361060475760003560e01c806325093e1b14604c578063b29a8ff4146065578063ede3150214606c575b600080fd5b6053602481565b60405190815260200160405180910390f35b6053601481565b605360348156fea2646970667358221220da135c71a84f8772d340dad3ef25a88ef16c8f7e3feb19b238a41a8d27cf79ca64736f6c634300081d0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "UserOperationLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;
  export function deployContract(
    contractName: "@account-abstraction/contracts/core/UserOperationLib.sol:UserOperationLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "UserOperationLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<UserOperationLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@account-abstraction/contracts/core/UserOperationLib.sol:UserOperationLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<UserOperationLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "UserOperationLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "@account-abstraction/contracts/core/UserOperationLib.sol:UserOperationLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;
}
