// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Proxy$Type } from "./Proxy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Proxy"]: Proxy$Type;
    ["@openzeppelin/contracts/proxy/Proxy.sol:Proxy"]: Proxy$Type;
  }

  interface ContractTypesMap {
    ["Proxy"]: GetContractReturnType<Proxy$Type["abi"]>;
    ["@openzeppelin/contracts/proxy/Proxy.sol:Proxy"]: GetContractReturnType<Proxy$Type["abi"]>;
  }
}
