// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Proxy$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Proxy",
  "sourceName": "@openzeppelin/contracts/proxy/Proxy.sol",
  "abi": [
    {
      "stateMutability": "payable",
      "type": "fallback"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Proxy",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Proxy$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/proxy/Proxy.sol:Proxy",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Proxy$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Proxy",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Proxy$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/proxy/Proxy.sol:Proxy",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Proxy$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Proxy",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Proxy$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/proxy/Proxy.sol:Proxy",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Proxy$Type["abi"]>>;
}
