// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPaymaster$Type } from "./IPaymaster";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPaymaster"]: IPaymaster$Type;
    ["@account-abstraction/contracts/interfaces/IPaymaster.sol:IPaymaster"]: IPaymaster$Type;
  }

  interface ContractTypesMap {
    ["IPaymaster"]: GetContractReturnType<IPaymaster$Type["abi"]>;
    ["@account-abstraction/contracts/interfaces/IPaymaster.sol:IPaymaster"]: GetContractReturnType<IPaymaster$Type["abi"]>;
  }
}
