// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IAggregator$Type } from "./IAggregator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IAggregator"]: IAggregator$Type;
    ["@account-abstraction/contracts/interfaces/IAggregator.sol:IAggregator"]: IAggregator$Type;
  }

  interface ContractTypesMap {
    ["IAggregator"]: GetContractReturnType<IAggregator$Type["abi"]>;
    ["@account-abstraction/contracts/interfaces/IAggregator.sol:IAggregator"]: GetContractReturnType<IAggregator$Type["abi"]>;
  }
}
