// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Exec$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Exec",
  "sourceName": "@account-abstraction/contracts/utils/Exec.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220dddad42553536c65dc6130ed848d384d2292fb0e7325d57edbaa9cdc6d31b16e64736f6c634300081d0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220dddad42553536c65dc6130ed848d384d2292fb0e7325d57edbaa9cdc6d31b16e64736f6c634300081d0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Exec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Exec$Type["abi"]>>;
  export function deployContract(
    contractName: "@account-abstraction/contracts/utils/Exec.sol:Exec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Exec$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Exec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Exec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@account-abstraction/contracts/utils/Exec.sol:Exec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Exec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Exec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Exec$Type["abi"]>>;
  export function getContractAt(
    contractName: "@account-abstraction/contracts/utils/Exec.sol:Exec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Exec$Type["abi"]>>;
}
