// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SenderCreator$Type } from "./SenderCreator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SenderCreator"]: SenderCreator$Type;
    ["@account-abstraction/contracts/core/SenderCreator.sol:SenderCreator"]: SenderCreator$Type;
  }

  interface ContractTypesMap {
    ["SenderCreator"]: GetContractReturnType<SenderCreator$Type["abi"]>;
    ["@account-abstraction/contracts/core/SenderCreator.sol:SenderCreator"]: GetContractReturnType<SenderCreator$Type["abi"]>;
  }
}
