// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SenderCreator$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SenderCreator",
  "sourceName": "@account-abstraction/contracts/core/SenderCreator.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "initCode",
          "type": "bytes"
        }
      ],
      "name": "createSender",
      "outputs": [
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x6080604052348015600f57600080fd5b506102038061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063570e1a3614610030575b600080fd5b61004361003e3660046100ec565b61005f565b6040516001600160a01b03909116815260200160405180910390f35b60008061006f6014828587610160565b6100789161018a565b60601c9050600061008c8460148188610160565b8080601f016020809104026020016040519081016040528093929190818152602001838380828437600092018290525084519495509360209350849250905082850182875af190506000519350806100e357600093505b50505092915050565b600080602083850312156100ff57600080fd5b823567ffffffffffffffff81111561011657600080fd5b8301601f8101851361012757600080fd5b803567ffffffffffffffff81111561013e57600080fd5b85602082840101111561015057600080fd5b6020919091019590945092505050565b6000808585111561017057600080fd5b8386111561017d57600080fd5b5050820193919092039150565b80356bffffffffffffffffffffffff1981169060148410156101c6576001600160601b03196001600160601b03198560140360031b1b82161691505b509291505056fea2646970667358221220584e070ad99cbcbf4377f0ee49015a8f9b469cfca596e716af3dc72e277c71bb64736f6c634300081d0033",
  "deployedBytecode": "0x608060405234801561001057600080fd5b506004361061002b5760003560e01c8063570e1a3614610030575b600080fd5b61004361003e3660046100ec565b61005f565b6040516001600160a01b03909116815260200160405180910390f35b60008061006f6014828587610160565b6100789161018a565b60601c9050600061008c8460148188610160565b8080601f016020809104026020016040519081016040528093929190818152602001838380828437600092018290525084519495509360209350849250905082850182875af190506000519350806100e357600093505b50505092915050565b600080602083850312156100ff57600080fd5b823567ffffffffffffffff81111561011657600080fd5b8301601f8101851361012757600080fd5b803567ffffffffffffffff81111561013e57600080fd5b85602082840101111561015057600080fd5b6020919091019590945092505050565b6000808585111561017057600080fd5b8386111561017d57600080fd5b5050820193919092039150565b80356bffffffffffffffffffffffff1981169060148410156101c6576001600160601b03196001600160601b03198560140360031b1b82161691505b509291505056fea2646970667358221220584e070ad99cbcbf4377f0ee49015a8f9b469cfca596e716af3dc72e277c71bb64736f6c634300081d0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SenderCreator",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SenderCreator$Type["abi"]>>;
  export function deployContract(
    contractName: "@account-abstraction/contracts/core/SenderCreator.sol:SenderCreator",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SenderCreator$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SenderCreator",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SenderCreator$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@account-abstraction/contracts/core/SenderCreator.sol:SenderCreator",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SenderCreator$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SenderCreator",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SenderCreator$Type["abi"]>>;
  export function getContractAt(
    contractName: "@account-abstraction/contracts/core/SenderCreator.sol:SenderCreator",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SenderCreator$Type["abi"]>>;
}
