version: '3.8'
services:
  app:
    image: wakeup-alto-bundler-local:latest
    build:
      context: .
      args:
        - BUNDLER_VERSION=v1.2.2
    ports:
      - "4337:4337"
    network_mode: host
    command: [
        "--entrypoints", "0x5FbDB2315678afecb367f032d93F642f64180aa3",
        "--executor-private-keys", "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d,0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a",
        "--utility-private-key", "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80", 
        "--rpc-url", "http://host.docker.internal:8545",
        "--port", "4337",
        "--deploy-simulations-contract", "true",
        "--chain-type","op-stack",
        "--safe-mode", "false"
    ]
