// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { UUPSUpgradeable$Type } from "./UUPSUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["UUPSUpgradeable"]: UUPSUpgradeable$Type;
    ["@openzeppelin/contracts/proxy/utils/UUPSUpgradeable.sol:UUPSUpgradeable"]: UUPSUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["UUPSUpgradeable"]: GetContractReturnType<UUPSUpgradeable$Type["abi"]>;
    ["@openzeppelin/contracts/proxy/utils/UUPSUpgradeable.sol:UUPSUpgradeable"]: GetContractReturnType<UUPSUpgradeable$Type["abi"]>;
  }
}
