// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { WakeUpPaymaster$Type } from "./WakeUpPaymaster";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["WakeUpPaymaster"]: WakeUpPaymaster$Type;
    ["contracts/Paymaster.sol:WakeUpPaymaster"]: WakeUpPaymaster$Type;
  }

  interface ContractTypesMap {
    ["WakeUpPaymaster"]: GetContractReturnType<WakeUpPaymaster$Type["abi"]>;
    ["contracts/Paymaster.sol:WakeUpPaymaster"]: GetContractReturnType<WakeUpPaymaster$Type["abi"]>;
  }
}
