// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TokenCallbackHandler$Type } from "./TokenCallbackHandler";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TokenCallbackHandler"]: TokenCallbackHandler$Type;
    ["@account-abstraction/contracts/samples/callback/TokenCallbackHandler.sol:TokenCallbackHandler"]: TokenCallbackHandler$Type;
  }

  interface ContractTypesMap {
    ["TokenCallbackHandler"]: GetContractReturnType<TokenCallbackHandler$Type["abi"]>;
    ["@account-abstraction/contracts/samples/callback/TokenCallbackHandler.sol:TokenCallbackHandler"]: GetContractReturnType<TokenCallbackHandler$Type["abi"]>;
  }
}
