// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IBeacon$Type } from "./IBeacon";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IBeacon"]: IBeacon$Type;
    ["@openzeppelin/contracts/proxy/beacon/IBeacon.sol:IBeacon"]: IBeacon$Type;
  }

  interface ContractTypesMap {
    ["IBeacon"]: GetContractReturnType<IBeacon$Type["abi"]>;
    ["@openzeppelin/contracts/proxy/beacon/IBeacon.sol:IBeacon"]: GetContractReturnType<IBeacon$Type["abi"]>;
  }
}
