// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ECDSA$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ECDSA",
  "sourceName": "@openzeppelin/contracts/utils/cryptography/ECDSA.sol",
  "abi": [
    {
      "inputs": [],
      "name": "ECDSAInvalidSignature",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "length",
          "type": "uint256"
        }
      ],
      "name": "ECDSAInvalidSignatureLength",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "s",
          "type": "bytes32"
        }
      ],
      "name": "ECDSAInvalidSignatureS",
      "type": "error"
    }
  ],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220528dd5465c80ebc4c0ba31d9ffd15702758de66ed5491a12e17fbbeea495f2ba64736f6c634300081d0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220528dd5465c80ebc4c0ba31d9ffd15702758de66ed5491a12e17fbbeea495f2ba64736f6c634300081d0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ECDSA",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ECDSA$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/cryptography/ECDSA.sol:ECDSA",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ECDSA$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ECDSA",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ECDSA$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/cryptography/ECDSA.sol:ECDSA",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ECDSA$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ECDSA",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ECDSA$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/cryptography/ECDSA.sol:ECDSA",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ECDSA$Type["abi"]>>;
}
