// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC1822Proxiable$Type } from "./IERC1822Proxiable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC1822Proxiable"]: IERC1822Proxiable$Type;
    ["@openzeppelin/contracts/interfaces/draft-IERC1822.sol:IERC1822Proxiable"]: IERC1822Proxiable$Type;
  }

  interface ContractTypesMap {
    ["IERC1822Proxiable"]: GetContractReturnType<IERC1822Proxiable$Type["abi"]>;
    ["@openzeppelin/contracts/interfaces/draft-IERC1822.sol:IERC1822Proxiable"]: GetContractReturnType<IERC1822Proxiable$Type["abi"]>;
  }
}
