// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { StakeManager$Type } from "./StakeManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StakeManager"]: StakeManager$Type;
    ["@account-abstraction/contracts/core/StakeManager.sol:StakeManager"]: StakeManager$Type;
  }

  interface ContractTypesMap {
    ["StakeManager"]: GetContractReturnType<StakeManager$Type["abi"]>;
    ["@account-abstraction/contracts/core/StakeManager.sol:StakeManager"]: GetContractReturnType<StakeManager$Type["abi"]>;
  }
}
