// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC1967$Type } from "./IERC1967";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC1967"]: IERC1967$Type;
    ["@openzeppelin/contracts/interfaces/IERC1967.sol:IERC1967"]: IERC1967$Type;
  }

  interface ContractTypesMap {
    ["IERC1967"]: GetContractReturnType<IERC1967$Type["abi"]>;
    ["@openzeppelin/contracts/interfaces/IERC1967.sol:IERC1967"]: GetContractReturnType<IERC1967$Type["abi"]>;
  }
}
