// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Panic$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Panic",
  "sourceName": "@openzeppelin/contracts/utils/Panic.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122029fcb4098411bfb611720e9c813d833d8bf992f8b1cd471ea089190de2a037cd64736f6c634300081d0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122029fcb4098411bfb611720e9c813d833d8bf992f8b1cd471ea089190de2a037cd64736f6c634300081d0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Panic",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Panic",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Panic$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Panic$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Panic",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
}
