name: Build

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache pnpm dependencies
      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            node_modules
            packages/ui/node_modules
            packages/api/node_modules
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      # Install pnpm dependencies
      - name: Install pnpm dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

    outputs:
      cache-hit: ${{ steps.pnpm-cache.outputs.cache-hit }}
      
  # Job to build the UI
  build-ui:
    runs-on: ubuntu-latest
    needs: install

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4pnpm --filter ./packages/ui run build

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Restore cached dependencies
      - name: Restore pnpm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
            packages/ui/node_modules
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      # Run the build for the UI
      - name: Build UI
        run: pnpm --filter ./packages/ui run build