name: Deploy api

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
    inputs:
      PAYMASTER_ADDRESS:
        required: true
        type: string

jobs:
  # Job to Deploy the UI
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Restore cached dependencies
      - name: Restore pnpm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
            packages/ui/node_modules
            packages/api/node_modules
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          fail-on-cache-miss: true

      # Run the build for the UI
      - name: Deploy
        run: pnpm deploy:api:staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PAYMASTER_ADDRESS: ${{ inputs.PAYMASTER_ADDRESS }}
      
      # Output the API URL and store in GITHUB outputs
      - name: Output
        run: cat .env | sed -n 's/.*ServiceEndpoint = \"\(.*\)\"/\1/p'