name: Deploy ui

on:
  workflow_call:
    inputs:
      aws-access-key-id:
        description: 'AWS access key ID'
        type: string
        required: true
      aws-secret-access-key:
        description: 'AWS secret access key'
        required: false
        type: string
      aws-region:
        description: 'AWS region'
        type: string
        required: false
        default: 'us-east-1'

jobs:
  # Install dependencies
  call-install-workflow:
    uses: ./.github/workflows/install-deps.yml
      
  # Job to Deploy the UI
  deploy:
    runs-on: ubuntu-latest
    needs: call-install-workflow

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Restore cached dependencies
      - name: Restore pnpm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
            packages/ui/node_modules
            packages/api/node_modules
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          fail-on-cache-miss: true

      # Run the build for the UI
      - name: Deploy
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_REGION=${{ env.AWS_REGION }}"
          pnpm deploy:app:staging
        env:
          AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
          AWS_REGION: ${{ inputs.aws-region }}