name: Staging

on:
  pull_request:
    types: [opened, synchronize, reopened, converted_to_draft]

jobs:
  # Install dependencies
  call-install-workflow:
    uses: ./.github/workflows/install-deps.yml
  
  # Job to build the UI
  call-build-workflow:
    uses: ./.github/workflows/Build.yml
    needs: call-install-workflow