name: Staging

on:
  pull_request:
    types: [opened, synchronize, reopened, converted_to_draft]

jobs:
  # call-build-workflow:
    # uses: ./.github/workflows/Build.yml

  call-deploy-ui-workflow:
    uses: ./.github/workflows/deploy-ui.yml