name: Staging

on:
  pull_request:
    types: [opened, synchronize, reopened, converted_to_draft]

jobs:
  call-build-workflow:
    uses: ./.github/workflows/Build.yml

  call-deploy-ui-workflow:
    uses: ./.github/workflows/deploy-ui.yml
    needs: call-build-workflow
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}